language: scala

scala:
  - 2.11.2
  - 2.10.4

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  # Disabled due to https://github.com/HaxeFoundation/haxe/issues/4220
  # - openjdk6

env:
  matrix:
    - SBT_COMMAND=test;test:run HAXE_TARGET=java HAXE_FILE=haxe_2015-05-12_master_77d171b.tar.gz
    - SBT_COMMAND=test;test:run HAXE_TARGET=java HAXE_FILE=haxe_2014-10-21_development_a05b532.tar.gz
    - SBT_COMMAND=test-csharp:run HAXE_TARGET=cs HAXE_FILE=haxe_2015-05-12_master_77d171b.tar.gz

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq neko ocaml
 - travis_retry wget http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/"$HAXE_FILE"
 - sudo tar zxvf "$HAXE_FILE"
 - sudo mv haxe-*/ haxe/
 - export PATH=$PATH:`pwd`/haxe
 - export HAXE_STD_PATH=`pwd`/haxe/std
 - travis_retry haxelib setup .haxelib-local
 - if [[ "$HAXE_TARGET" = "java" ]]; then travis_retry haxelib install hxjava --always; fi
 - if [[ "$HAXE_TARGET" = "cs" ]]; then travis_retry sudo apt-get install mono-devel; fi
 - if [[ "$HAXE_TARGET" = "cs" ]]; then travis_retry haxelib install hxcs --always; fi
 - travis_retry haxelib install HUGS 0.3.0 --always
 - travis_retry haxelib install continuation 1.3.2 --always

script: sbt ";++$TRAVIS_SCALA_VERSION;$SBT_COMMAND"
