sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

language: scala

addons:
  apt:
    packages:
    - mono-devel
    - libgc1c2

before_install:
 - travis_retry wget http://nekovm.org/media/neko-2.0.0-linux64.tar.gz
 - tar zxvf neko-2.0.0-linux64.tar.gz
 - travis_retry wget http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/"$HAXE_FILE"
 - tar zxvf "$HAXE_FILE"
 - mv haxe-*/ haxe/
 - export PATH=$PATH:$PWD/haxe:$PWD/neko-2.0.0-linux
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/neko-2.0.0-linux
 - export HAXE_STD_PATH=$PWD/haxe/std
 - haxelib setup .haxelib-local
 - if [[ "$HAXE_TARGET" = "java" ]]; then travis_retry haxelib install hxjava --always; fi
 - if [[ "$HAXE_TARGET" = "cs" ]]; then travis_retry haxelib install hxcs --always; fi

script:
  - sbt ";++$TRAVIS_SCALA_VERSION;haxelibInstallDependencies;$SBT_COMMAND"

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

scala:
  - 2.11.2
  - 2.10.4

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  # Disabled due to https://github.com/HaxeFoundation/haxe/issues/4220
  # - openjdk6

env:
  matrix:
    - SBT_COMMAND=test;test:run HAXE_TARGET=java HAXE_FILE=haxe_2015-05-12_master_77d171b.tar.gz
    - SBT_COMMAND=test-csharp:run HAXE_TARGET=cs HAXE_FILE=haxe_2015-05-12_master_77d171b.tar.gz
